// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxkxyxnuxqdjbwvxineh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4a3h5eG51eHFkamJ3dnhpbmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDEwNzEsImV4cCI6MjA2NzgxNzA3MX0.UI18n8Tm53L-rBI7d_L8YIGY0S-ZKtr97uB0hmIg8bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});